version: "3.6"

services:
  nodejs-hv-tp:
    build:
      context: ./node-hv-tp  #where search for the dockerfile
      dockerfile: Dockerfile
    command: |
              bash -c "
              cd /src/ && \
              npm install && \
              node index.js
              "
    volumes:
      - ./node-hv-tp/.:/src/

# UNCOMMENT IF YOU WANT TO RUN RUST TP
#  rust-hv-tp:
#    build:
#      context: ./rust-hv-tp  #where search for the dockerfile
#      dockerfile: Dockerfile
#     entrypoint: tail -f /dev/null 
#    volumes:
#      - ./rust-hv-tp/.:/rust-hv-tp/

# COMMENT IF YOU DON'T WANT TO ATTACH AN EXISTING NETWORK 
networks:
  default:
    external:
      name: 0-validator-sawtooth_default