version: "2.1"

services:
  nodejs-hv-tp:
    build:
      context: ./node-hv-tp  #where search for the dockerfile
      dockerfile: Dockerfile
    entrypoint: bash -c \"\
        cd /src/ && \
        npm install && \
        tail -f /dev/null
        \"" 
    volumes:
      - ./node-hv-tp/.:/src/
  rust-hv-tp:
    build:
      context: ./rust-hv-tp  #where search for the dockerfile
      dockerfile: Dockerfile
    entrypoint: tail -f /dev/null 
    volumes:
      - ./rust-hv-tp/.:/rust-hv-tp/